### ISSUE TITLE
即使是sudo npm install,还是在copyfile时提示permission denied

### ISSUE THREAD

**Issue by milobluebell** [juicecube/mlz-pack#9]
![image](https://user-images.githubusercontent.com/11535146/75849736-92053280-5e20-11ea-9b1a-9d9853d54719.png)

OS：mac catalina 10.15.3
Node: 10.16.3
Npm: 6.9.0
指令：sudo npm install @mlz/pack -D

**Comment by milobluebell** [comment]
chmod -R 777 之后可以解决，但是有没有其它方法？

**Comment by Fukiii** [comment]
试一下 npm config set unsafe-perm true

**Comment by milobluebell** [comment]
👌现在可以了
